[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))']
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    # LLD by default uses xxhash for build ids now, which breaks tests that assume
    # GUIDS or longer
    "-C",
    "link-arg=-Wl,--build-id=sha1",
]
